<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Pranav-Yadav" failures="2" tests="2" name="Default test(failed)" time="0.06" errors="0" timestamp="2022-05-28T16:35:15 IST">
  <testcase classname="TestNgRetryFailedTest.TestNgRetryFailedTestDemo" name="test2" time="0.01">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at TestNgRetryFailedTest.TestNgRetryFailedTestDemo.test2(TestNgRetryFailedTestDemo.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="TestNgRetryFailedTest.TestNgRetryFailedTestDemo" name="test3" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNgRetryFailedTest.TestNgRetryFailedTestDemo.test3(TestNgRetryFailedTestDemo.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="TestNgRetryFailedTest.TestNgRetryFailedTestDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
